appium:
  app: ""
  url: http://127.0.0.1:4723/wd/hub
  wait: 6
  platformName: ios #不同平台修改该值
  androidcapabilities:
    platformName: android
    platformVersion: 7.1.1
    deviceName: test
    appPackage: com.iqianjin.client
    appActivity: asurface.activity.StartActivity
    unicodeKeyboard: true
    resetKeyboard: true
    #automationName: UiAutomator2
    printPageSourceOnFindFailure: true
    noReset: true
  ioscapabilities:
    platformName: iOS
    deviceName: iphone6p
    platformVersion: 10.3.2
    bundleId: com.iqianjin.iqianjinplus
    udid: 9a98c5f70037dbaaff8fa23839f83d3f3aae158f
    automationName: XCUITest
    #noReset: true
    wdaStartupRetries: 2
    #iosInstallPause: 8000
    wdaStartupRetryInterval: 20000
    showXcodeLog: true
    #showIOSLog: true
