appium:
  app: ""
  url: http://127.0.0.1:4723/wd/hub
  wait: 6
  platName: android #换手机修改此值
  androidCapabilities:
    platformName: android
    platformVersion: 7.1.1
    deviceName: test
    appPackage: com.iqianjin.client
    appActivity: asurface.activity.StartActivity
    unicodeKeyboard: true
    resetKeyboard: true
    newCommandTimeout: 300
    automationName: UiAutomator2
    autoGrantPermission: true
    printPageSourceOnFindFailure: true
    noReset: true
  iosCapabilities:
    platformName: ios
    platformVersion: 10.3.2
    wdaLocalPort: 8100
    deviceName: iphone6p
    bundleId: com.iqianjin.iqianjinplus
    udid: 9a98c5f70037dbaaff8fa23839f83d3f3aae158f
    automationName: XCUITest
    printPageSourceOnFindFailure: true
    noReset: true
    startIWDP: true
    wdaStartupRetries: 2
    wdaStartupRetryInterval: 2000
    newCommandTimeout: 300
    #iosInstallPause: 8000
    #showXcodeLog: true
    #showIOSLog: true





